<?php

namespace Versionable\Tests\Prospect\Adapter;

use Versionable\Prospect\Adapter\AdapterAbstract;

/**
 * Test class for AdapterAbstract.
 * Generated by PHPUnit on 2011-04-08 at 08:43:07.
 */
class AdapterAbstractTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var AdapterAbstract
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = $this->getMockForAbstractClass('Versionable\\Prospect\\Adapter\\AdapterAbstract');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  public function testSetOption()
  {
    $this->object->setOption('foo', 'bar');
    $actual = $this->object->getOption('foo');

    $this->assertEquals('bar', $actual);
  }

  public function testHasOption()
  {
    $this->assertFalse($this->object->hasOption('foo'));
    $this->object->setOption('foo', 'bar');
    $this->assertTrue($this->object->hasOption('foo'));
    $actual = $this->object->getOption('foo');

    $this->assertEquals('bar', $actual);
  }

  public function testGetNonExistentOption()
  {
    $this->setExpectedException('\\Versionable\\Prospect\\Adapter\\Exception\\AdapterAbstractException');

    $actual = $this->object->getOption('foo');
  }
}

